---
- name: setup agent service
  service:
    name: newrelic-infra
    state: "{{ nrinfragent_service_state }}"
    enabled: "{{ nrinfragent_service_enabled }}"
  when:
    - nrinfragent_state != "absent"
    - nrinfragent_os_name != 'windows'

- name: setup agent service
  win_service:
    name: newrelic-infra
    state: "{{ nrinfragent_service_state }}"
  when:
    - nrinfragent_state != "absent"
    - nrinfragent_os_name == 'windows'