---
- name: Confirm RedHat lsb util is present
  yum: name=redhat-lsb-core state=present
  when: nrinfragent_os_name|lower == 'redhat'

- name: Reread ansible_lsb facts
  setup: filter=ansible_lsb*
  when: nrinfragent_os_name|lower == 'redhat'

- name: setup agent repo keys
  apt_key:
    url: https://download.newrelic.com/infrastructure_agent/gpg/newrelic-infra.gpg
    state: present
  when: nrinfragent_os_name|lower == 'debian'

- name: setup agent repo keys
  rpm_key:
    key: https://download.newrelic.com/infrastructure_agent/gpg/newrelic-infra.gpg
    state: present
  when: nrinfragent_os_name|lower == 'redhat'

- name: setup agent repo keys
  rpm_key:
    key: https://download.newrelic.com/infrastructure_agent/gpg/newrelic-infra.gpg
    state: present
  when: nrinfragent_os_name|lower == 'suse'

- name: Confirm Debian apt-transport-https is present
  apt:
    name: apt-transport-https
    state: present
  when: nrinfragent_os_name|lower == 'debian'

- name: setup agent repo reference
  apt_repository:
    repo: "deb [arch=amd64] https://download.newrelic.com/infrastructure_agent/linux/apt {{ nrinfragent_os_codename }} main"
    state: present
    update_cache: "yes"
  when: nrinfragent_os_name|lower == 'debian'

- name: setup agent repo reference
  yum_repository:
    baseurl: "https://download.newrelic.com/infrastructure_agent/linux/yum/el/{{ (ansible_service_mgr == 'upstart') | ternary('6', '7') }}/x86_64"
    gpgcheck: "yes"
    gpgkey: https://download.newrelic.com/infrastructure_agent/gpg/newrelic-infra.gpg
    name: 'newrelic-infra'
    repo_gpgcheck: 'yes'
    state: present
    description: New Relic Infrastructure
  when: ansible_distribution|lower == 'amazon'
  register: setup_agent_repo

- name: setup agent repo reference
  yum_repository:
    baseurl: "https://download.newrelic.com/infrastructure_agent/linux/yum/el/{{ nrinfragent_os_version }}/x86_64"
    gpgcheck: "yes"
    gpgkey: https://download.newrelic.com/infrastructure_agent/gpg/newrelic-infra.gpg
    name: 'newrelic-infra'
    repo_gpgcheck: "{{ (nrinfragent_os_version == '5') | ternary('no', 'yes') }}"
    state: present
    description: New Relic Infrastructure
  when: nrinfragent_os_name|lower == 'redhat' and ansible_distribution|lower != 'amazon'
  register: setup_agent_repo

- name: setup agent repo reference
  zypper_repository:
    name: newrelic-infra
    description: New Relic Infrastructure Agent
    repo: "http://download.newrelic.com/infrastructure_agent/linux/zypp/sles/{{ ansible_distribution_version }}/{{ ansible_machine }}/"
    runrefresh: "yes"
    auto_import_keys: "yes"
    disable_gpg_check: "yes"
  when: nrinfragent_os_name|lower == 'suse'
  register: infra_agent_zypper_repo

- name: run make cache to actually import gpg key
  command: "yum -q makecache -y --disablerepo='*' --enablerepo='newrelic-infra'"
  when: nrinfragent_os_name|lower == 'redhat' and setup_agent_repo.changed
  tags:
    - skip_ansible_lint
  args:
    warn: false

- name: install agent
  package:
    name: "newrelic-infra"
    state: "{{ nrinfragent_state }}"

- name: install integrations
  package:
    name: "newrelic-infra-integrations"
    state: "{{ nrinfraintegrations_state }}"

- name: setup agent config
  template:
    src: newrelic-infra.yml.j2
    dest: /etc/newrelic-infra.yml
    mode: 0600
  notify: restart newrelic-infra
  when: nrinfragent_state != "absent"

- name: setup agent service
  service: name=newrelic-infra state=started enabled=yes
  when: nrinfragent_state != "absent"
