---
- name: installation from tarball package
  import_tasks: install_targz.yml
  tags:
    - install
    - tarball
  when:
    - nrinfragent_tarball_version is defined
    - nrinfragent_os_name != 'windows'


- name: install from standard distribution packages
  import_tasks: install_dist_pkgs.yml
  tags:
    - install
  when: nrinfragent_tarball_version is undefined

- name: install OHIs
  import_tasks: install_integrations_pkgs.yml
  tags:
    - integrations
  when: nrinfragent_tarball_version is undefined

- name: configure the infrastructure agent
  import_tasks: configure_agent.yml
  tags:
    - configure

- name: install agent os service
  import_tasks: install_agent_service.yml
  tags:
    - service