---
- name: custom installation from tar package
  import_tasks: install_targz.yml
  when: nrinfragent_custom_installation|bool

- name: install from standard distribution packages
  import_tasks: install_dist_pkgs.yml
  when: not (nrinfragent_custom_installation|bool)