---
- name: installation from tarball package
  import_tasks: install_targz.yml
  when: nrinfragent_tarball_version is defined

- name: install from standard distribution packages
  import_tasks: install_dist_pkgs.yml
  when: nrinfragent_tarball_version is undefined
