---
- name: Setup logging
  template:
    src: newrelic-logging.yml.j2
    dest: /etc/newrelic-infra/logging.d/logging.yml
  when:
    - nrinfragent_logging
    - nrinfragent_state != "absent"
    - nrinfragent_os_name != 'windows'

- name: setup logging (windows)
  win_template:
    src: newrelic-logging.yml.j2
    dest: C:\Program Files\New Relic\newrelic-infra\logging.d\logging.yml
  when:
    - nrinfragent_logging
    - nrinfragent_state != "absent"
    - nrinfragent_os_name == 'windows'
