blank_issues_enabled: false
contact_links:
  - name: Troubleshooting
    url:  https://github.com/newrelic/infrastructure-agent-ansible/blob/master/README.md#support
    about: Check out the README for troubleshooting directions
