---

- name: restart newrelic-infra
  service: name=newrelic-infra state=restarted
  when: nrinfragent_service_state != "stopped"

- name: running installer
  command: ./installer.sh
  args:
    chdir: "/opt/newrelic_infra/linux_{{ nrinfragent_custom_version }}_{{ nrinfragent_architecture }}/newrelic-infra/"
  environment:
    NRIA_BIN_DIR: "{{ nrinfragent_custom_bin_dir | default('') }}"
    NRIA_MODE: "{{ nrinfragent_custom_mode | default('') }}"
    NRIA_USER: "{{ nrinfragent_custom_user | default('') }}"
    NRIA_CONFIG_FILE: "{{ nrinfragent_custom_config_file | default('') }}"
    NRIA_PID_FILE: "{{ nrinfragent_custom_pid_file | default('') }}"
    NRIA_AGENT_DIR: "{{ nrinfragent_custom_agent_dir | default('') }}"
    NRIA_PLUGIN_DIR: "{{ nrinfragent_custom_plugin_dir | default('') }}"
    NRIA_LOG_FILE: "{{ nrinfragent_custom_log_file | default('') }}"
    NRIA_LICENSE_KEY: "{{ nrinfragent_license_key | default('') }}"
  become: true
