---
- name: Converge
  hosts: all
  tasks:
    - name: "Include infrastructure-agent-ansible"
      include_role:
        name: "infrastructure-agent-ansible"
      vars:
        nrinfragent_config:
          license_key: Q000000000000000000000000000000000000000
          custom_attributes:
            team: 'newrelic'
            business_unit: 'engineering'
        nrinfragent_logging:
          - name: file test
            file: /var/log/messages
          - name: syslog udp test
            syslog:
              uri: udp://0.0.0.0:6140
              parser: rfc5424
            max_line_kb: 35
          - name: syslog-unix-tcp-test
            syslog:
              uri: unix_tcp:///var/unix-tcp-socket-test
              unix_permissions: 0666
          - name: tcp-json-test
            tcp:
              uri: tcp://0.0.0.0:2345
              format: json