FROM amazonlinux:2

# Run a system update so the system doesn't overwrite the fake systemctl later
RUN yum -y update
# Install sudo which is required by targz installation script
RUN yum -y install sudo

# Adding fake systemctl and python
RUN curl https://raw.githubusercontent.com/gdraheim/docker-systemctl-replacement/master/files/docker/systemctl3.py -o /usr/bin/systemctl \
 && yum install python3 -y
