on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
name: Test

jobs:
  test_ansible:
    runs-on: ubuntu-latest
    name: Run linter and tests
    steps:
      - uses: actions/checkout@v2
      - name: Install requirements
        uses: newrelic/infrastructure-agent-ansible/.github/actions/installation@master
      - name: Run linter
        uses: newrelic/infrastructure-agent-ansible/.github/actions/linter@master
      - name: Run tests
        uses: newrelic/infrastructure-agent-ansible/.github/actions/tests@master
