on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
name: Test

jobs:
  test_ansible:
    runs-on: ubuntu-latest
    name: Run linter and tests
    steps:
      - uses: actions/checkout@v2
      - name: Install requirements
        uses: ./.github/actions/installation
      - name: Run linter
        uses: ./.github/actions/linter
      - name: Run tests
        uses: ./.github/actions/tests
