on:
  release:
    type: [published]
    
name: Ansible Workflow

jobs:
  pre_release_test:
    runs-on: ubuntu-20.04
    name: Run linter and tests
    steps:
      - uses: actions/checkout@v2
      - name: Install requirements
        uses: newrelic/infrastructure-agent-ansible/.github/actions/installation@github-actions
      - name: Run linter
        uses: newrelic/infrastructure-agent-ansible/.github/actions/linter@github-actions
      - name: Run tests
        uses: newrelic/infrastructure-agent-ansible/.github/actions/tests@github-actions
  release_ansible:
    runs-on: ubuntu-20.04
    name: Release package
    needs: pre_release_test
    steps:
      - name: Release ansible
        uses: newrelic/infrastructure-agent-ansible/.github/actions/release@github-actions
        with:
          galaxy_api_key: ${{ secrets.galaxy_api_key }}
